<?php

/**
 * @file
 * Menu Pager block for each menu with previous and next link navigation.
 */

/**
 * Implements hook_menu_pager_ignore_paths().
 */
function menu_pager_menu_pager_ignore_paths($menu_name) {
  $paths = [];
  // Ignore Special Menu Items paths that don't actually link to anything.
  $paths[] = '<nolink>';
  $paths[] = '<separator>';

  return $paths;
}

/**
 * Implements hook_theme().
 */
function menu_pager_theme($existing, $type, $theme, $path) {
  return [
    'menu_pager' => [
      'variables' => [
        'previous' => NULL,
        'next' => NULL,
      ],
    ],
  ];
}
