<?php

/**
 * @file
 *
 * Menu Pager adds a block for each menu that adds previous
 * and next link navigation based on the current page.
 */

/**
 * Implements hook_menu_pager_ignore_paths().
 */
function menu_pager_menu_pager_ignore_paths($menu_name) {
  $paths = [];
  // Ignore Special Menu Items paths that don't actually link to anything.
  $paths[] = '<nolink>';
  $paths[] = '<separator>';

  return $paths;
}
